config/routes.rb
Rails.application.routes.draw do

  resources :events
  post 'reviews/edit', :to => "reviews#edit"
  get 'tutorings/index'
  get 'tutorings/new'
  get 'tutorings/edit'
  get 'tutorings/show'
  get 'tutorings/list'

  post '/rate' => 'rater#create', :as => 'rate'

  get 'fbsessions/create'
  get 'fbsessions/destroy'
  get 'fbsessions/create'
  get 'fbsessions/destroy'
  get 'sessions/create'
  get 'sessions/destroy'

  get 'home/show'

  get "signup", :to => "users#new"
  get "login", :to => "sessions#login"
  get "logout", :to => "sessions#logout"
  get "home", :to => "sessions#home"

  get "setting", :to => "sessions#setting"

  get 'users/list', to: "users#list"
  get 'courses/download', to: "courses#download_request"
  post 'courses/download', to: "courses#download"
  post 'login', :to => "sessions#login_attempt"

  get 'users/new'
  get 'courses/index'
  get 'courses/new'
  get 'posts/index'
  get 'user/profile'
  get 'user/show'
  get 'user/register'
  get 'user/login'
  get 'messageboard/index'
  get 'messageboard/new'
  get 'messageboard/show'

  resources :widgets
  resources :users
  resources :fbsessions
  resources :reviews
  resources :tutorings
  resources :courses do
    member do
      get :subscribe
    end
  end

  resources :messageboard do
    resources :posts
    member do
      get :subscribe
    end
  end
  resources :topic do
    resources :posts
  end
  resources :posts do
    resources :posts
    member do
      put "like", to: "posts#upvote"
      put "dislike", to: "posts#downvote"
    end
  end

  resources :notifications do
    collection do
      post :mark_as_read
    end
  end
  scope '/users' do
    resources :conversations do
      resources :messages
    end
  end

  resources :conversations do
    resources :messages
  end

  get 'auth/:provider/callback', to: 'fbsessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'fbsessions#destroy', as: 'signout'

  resources :fbsessions, only: [:create, :destroy]
  resource :home, only: [:show]

  root to: "courses#index"
  get 'calendars', to: 'calendars#index'

  get '/redirect', to: 'fbsessions#redirect', as: 'redirect'
  get '/callback', to: 'fbsessions#callback', as: 'callback'

end

app/models/tutoring.rb
class Tutoring < ActiveRecord::Base
  belongs_to :user
  belongs_to :course

end

app/controllers/tutorings_controller.rb
class TutoringsController < ApplicationController
before_action :find_tutoring, only: [:show, :edit, :update, :destroy]

  def index
  	@tutorings = Tutoring.where(:user_id => current_user.id)
    @user = User.where(:id => current_user.id)
  end

  def new
  	@tutoring = Tutoring.new()
  end

  def create
   	@tutoring = Tutoring.new(tutoring_params)
    @tutoring.user_id = current_user.id
    if @tutoring.save
      flash[:notice] = "Successfully added course"
      redirect_to tutorings_path
    else
      flash[:notice] = "Course not added. Please double-check your input."
 	    render 'new'
    end
  end

  def edit
  end

  def update
    if @tutoring.update(tutoring_params)
      flash[:notice] = "Information updated"
      redirect_to tutorings_path
    else
      flash[:notice] = "Failed to update"
      render 'edit'
    end
  end

  def destroy
    flash[:notice] = "Deleted #{@tutoring.course}"
  	@tutoring.destroy
  	redirect_to tutorings_path
  end

  def list
    @tutorings = Tutoring.where(:course_id => params[:course])
    @course = Course.find(params[:course])
  end

  private
  	def tutoring_params
  		params.require(:tutoring).permit(:user_id, :course_id, :hourly, :mode, :description)
	  end

    def find_tutoring
      @tutoring = Tutoring.find(params[:id])
    end


end

app/helpers/tutorings_helper.rb
module TutoringsHelper
end

app/views/tutorings/edit.html.erb
<h1>Edit Information</h1>

<%= form_for(@tutoring) do |t| %>
  <p>Course: <%= t.collection_select :course_id, Course.order(:name, :term), :id, :term_and_name, :include_blank => true %></p>
  <p>Hourly rate: <%= t.number_field :hourly, :class => 'text_field', :step => 0.01 %></p>
  <!-- add in field for mode of delivery if I have time -->
  <p>Description: <%= t.text_field :description, :size => 100 %> </br>(enter any additional info you want, e.g. if you've tutored or TA'd for this course before, with this specific prof, etc.)</p>
  <%= t.submit "Update" %>

<% end %>

<br>
<a href=<%= tutorings_path(:id => current_user.id) %>>Back</a>

app/views/tutorings/index.html.erb
<h1>Courses I'm Tutoring</h1>
<p><%= link_to "Add Course", new_tutoring_path %></p>

<table id='tutoringsTable'>
	<col width = '150'>
	<col width = '500'>
	<col width = '150'>
	<col width = '500'>
	<tr class='header'>
		<th>Term</th>
		<th>Course</th>
		<th>Hourly rate</th>
		<th>Description</th>
		<th>Edit</th>
		<th>Delete</th>
	</tr>
	<% @tutorings.order(:id).each do |tutoring| %>
		<tr>
			<% @course = Course.where(:id => tutoring.course_id).first %>
			<td><%= @course.term %></td>
			<td><%= @course.name %></td>
			<td><%= number_with_precision(tutoring.hourly, :precision => 2) %></td>
			<td><%= tutoring.description %></td>
			<td><%= link_to 'Edit', edit_tutoring_path(tutoring) %></td>
			<td><%= link_to 'Delete', tutoring, method: :delete, data: { confirm: 'Are you sure?' } %></td>
		</tr>
	<% end %>
</table>

<br>
<a href=<%= user_path(:id=>current_user.id) %>>Back</a>

app/views/tutorings/list.html.erb
<h1>Tutors for <%= @course.name %></h1>
<table>
	<tr>
		<th>Tutor Username</th>
		<th>Hourly Rate</th>
		<th>Description</th>
		<th>Tutor Email</th>		
	</tr>
	<% @tutorings.each do |t| %>
		<% @tutor = User.where(:id => t.user_id).first %>
		<% if @tutor.tutor %>
			<tr>
				<% @tutor = User.where(:id => t.user_id).first %>
				<td><%= link_to @tutor.username, user_path(:id => @tutor.id) %></td>
				<td><%= t.hourly %></td>
				<td><%= t.description %></td>
				<td><%= @tutor.email %></td>
			</tr>
		<% end %>
	<% end %>
</table>

app/views/tutorings/new.html.erb
<h1>Add Course to Tutor</h1>

<%= form_for Tutoring.new do |t| %>
  <p>Course: <%= t.collection_select :course_id, Course.order(:name, :term), :id, :term_and_name, :include_blank => true %></p>
  <p>Hourly rate: <%= t.number_field :hourly, :class => 'text_field', :step => 0.01 %></p>
  <!-- add in field for mode of delivery if I have time -->
  <p>Description: <%= t.text_field :description, :size => 100 %> </br>(enter any additional info you want, e.g. if you've tutored or TA'd for this course before, modes of delivery, group tutoring rates, etc.)</p>
  <%= t.submit "Add" %>
<% end %>

<br>
<a href=<%= tutorings_path(:id => current_user.id) %>>Back</a>

app/views/tutorings/show.html.erb
<h1>Tutorings#show</h1>
<p>Find me in app/views/tutorings/show.html.erb</p>