config/routes.rb
Rails.application.routes.draw do

  resources :events
  post 'reviews/edit', :to => "reviews#edit"
  get 'tutorings/index'
  get 'tutorings/new'
  get 'tutorings/edit'
  get 'tutorings/show'
  get 'tutorings/list'

  post '/rate' => 'rater#create', :as => 'rate'

  get 'fbsessions/create'
  get 'fbsessions/destroy'
  get 'fbsessions/create'
  get 'fbsessions/destroy'
  get 'sessions/create'
  get 'sessions/destroy'

  get 'home/show'

  get "signup", :to => "users#new"
  get "login", :to => "sessions#login"
  get "logout", :to => "sessions#logout"
  get "home", :to => "sessions#home"

  get "setting", :to => "sessions#setting"

  get 'users/list', to: "users#list"
  get 'courses/download', to: "courses#download_request"
  post 'courses/download', to: "courses#download"
  post 'login', :to => "sessions#login_attempt"

  get 'users/new'
  get 'courses/index'
  get 'courses/new'
  get 'posts/index'
  get 'user/profile'
  get 'user/show'
  get 'user/register'
  get 'user/login'
  get 'messageboard/index'
  get 'messageboard/new'
  get 'messageboard/show'

  resources :widgets
  resources :users
  resources :fbsessions
  resources :reviews
  resources :tutorings
  resources :courses do
    member do
      get :subscribe
    end
  end

  resources :messageboard do
    resources :posts
    member do
      get :subscribe
    end
  end
  resources :topic do
    resources :posts
  end
  resources :posts do
    resources :posts
    member do
      put "like", to: "posts#upvote"
      put "dislike", to: "posts#downvote"
    end
  end

  resources :notifications do
    collection do
      post :mark_as_read
    end
  end
  scope '/users' do
    resources :conversations do
      resources :messages
    end
  end

  resources :conversations do
    resources :messages
  end

  get 'auth/:provider/callback', to: 'fbsessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'fbsessions#destroy', as: 'signout'

  resources :fbsessions, only: [:create, :destroy]
  resource :home, only: [:show]

  root to: "courses#index"
  get 'calendars', to: 'calendars#index'

  get '/redirect', to: 'fbsessions#redirect', as: 'redirect'
  get '/callback', to: 'fbsessions#callback', as: 'callback'

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
before_action :find_course, only: [:show, :edit, :update, :destroy]

  # Default view shows all courses
  def index
    @courses = Course.all
  end

  # Add new course
  def new
  	@course = Course.new
  end

  # Create new course
  def create
   	@course = Course.new(course_params)
    @course.term = @course.term.capitalize
    if @course.save
      flash[:notice] = "Successfully added #{@course.name}"
      redirect_to courses_path
    else
      flash[:notice] = "Course not added. Please double-check your input."
 	    render 'new'
    end
  end

  # Edit course. I don't remember why I set up edit and update as separate methods
  # but I don't want to tinker with this now
  def edit
  end

  def update
    if @course.update(course_params)
      flash[:notice] = "Course updated"
      redirect_to courses_path
    else
      flash[:notice] = "Course failed to update"
      render 'edit'
    end
  end

  # Delete course
  def destroy
    flash[:notice] = "Deleted #{@course.name}"
  	@course.destroy
  	redirect_to courses_path
  end
  
  # Download courses
  def download
  end

  def subscribe
    @course = Course.find(params[:id])
    if current_user
      if current_user.following?(@course)
        current_user.stop_following(@course)
      else
        current_user.follow(@course)
      end
    else
      flash[:notice] = "You must log in to subscribe."
    end
    redirect_to :back
  end

  def tutors
    @course = Course.find(params[:id])
  end

  # These variables are used above
  private
  	def course_params
  		params.require(:course).permit(:name, :term)
	  end

    def find_course
      @course = Course.find(params[:id])
    end

end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_event.html.erb
<% @events = Event.where(start:Date.yesterday..Date.tomorrow) %>

<%= render 'layouts/events' %>

app/views/courses/_form.html.erb
<%= form_for(@course) do |c| %>
	<p>Enter term of the course in the format "Spring 2018" (valid terms are "Spring", "Summer", or "Fall", and year must be between 2000 and 2099)</p>
	<%= c.label :term %>
	<%= c.text_field :term %><br><br>
	<p>Enter course name in the format "CMPT276: Introduction to Software Engineering"</p>
	<%= c.label :name %>
	<%= c.text_field :name %><br><br><br>
	<%= c.submit %><br><br>

<% end %>

app/views/courses/download.html.erb
<% if params[:year] !~ /\A20\d{2}\z/ %>
<% 		flash[:notice] = "Please enter a valid year" %>
<% 		controller.redirect_to courses_download_path %>
<% else %>
<%		base_url = 'http://www.sfu.ca/bin/wcm/course-outlines?' + params[:year] + '/' + params[:term] + '/' + params[:department] %>
<% 		rawcoursedata = RestClient.get (base_url) %>
<% 		coursedata = JSON.parse(rawcoursedata) %> 
<% 		courseterm = params[:term].capitalize + ' ' + params[:year] %>
<% 		coursedata.each do |course| %>
<%			coursename = params[:department].upcase + course['value'] + ': ' + course['title'] %><br>
<%			course = Course.new(:name => coursename, :term => courseterm) %>
<%			course.save %>
<% 		end %>
<% 		flash[:notice] = "Processing finished" %>
<% 		controller.redirect_to root_path %>
<% end %>

app/views/courses/download_request.html.erb
<h1>Auto-Populate Course Database</h1>
<p>Enter the year, term, and department you want to download course data for. The data are pulled via the SFU Course Outlines API.</p>

<%= form_tag do %>
	<%= label :year, "Year (e.g. '2018'): " %>
	<%= text_field_tag :year %>
	</br>
	<%= label :term, "Term: " %>
    	<%= radio_button_tag(:term, "spring") %> 
    	<%= label_tag(:term, "Spring") %>
    	<%= radio_button_tag(:term, "summer") %>
    	<%= label_tag(:term, "Summer") %>
      	<%= radio_button_tag(:term, "fall") %>
    	<%= label_tag(:term, "Fall") %>
  	</br>
	<%= label :term, "Department (e.g. 'CMPT', 'PSYC'): " %>
	<%= text_field_tag :department %><br><br>
	<%= submit_tag(value = "Download Course Data")%><br><br>
<% end %>

app/views/courses/edit.html.erb
<h1>Edit Course</h1>

<%= render 'form' %>

<p><%= link_to 'Cancel', courses_path %></p>

app/views/courses/index.html.erb
<head>
	<% provide :title, "Courses - Home" %>
	<%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
</head>
<h1>SFU Study Hub Message Board</h1>

<% if current_user && current_user.role == 'admin' %>
	<h3>Administrator Functions:</h3>
	<p><%= link_to "Manually Add Single Course", courses_new_path %></p>
	<p><%= link_to "Bulk Add Courses by Term and Department", courses_download_path %></p>
	<h3>Basic User Functions:</h3>
<% end %>

<script>
// This script is adapted from www.w3schools.com/howto/howto_js_filter_table.asp
function filterCourseTable() {
  // Declare variables
  var termInput, termFilter, courseInput, courseFilter, table, tr, td, i;
  termInput = document.getElementById("termFilter");
  termFilter = termInput.value.toUpperCase();
  courseInput = document.getElementById("courseFilter");
  courseFilter = courseInput.value.toUpperCase();
  table = document.getElementById("courseTable");
  tr = table.getElementsByTagName("tr");

  // Loop through all table rows, hiding those that don't match the search query
  for (i = 0; i < tr.length; i++) {
  	// Checking term column
  	tdTerm = tr[i].getElementsByTagName("td")[0];
  	tdCourse = tr[i].getElementsByTagName("td")[1];
    if (tdTerm && tdCourse) {
      if (tdTerm.innerHTML.toUpperCase().indexOf(termFilter) > -1 && tdCourse.innerHTML.toUpperCase().indexOf(courseFilter) > -1 ) {
        tr[i].style.display = "";
      } else {
        tr[i].style.display = "none";
      }
    }
  }
}
</script>

<div class="container2">
<p>Search by term or year: <input type='text' size='20' id='termFilter' onkeyup='filterCourseTable()' placeholder='Enter term or year'></p>
<p>Search by course number or name: <input type='text' size='40' id='courseFilter' onkeyup='filterCourseTable()' placeholder='Enter course number or name'></p>
</br>

<p>Click on a course name below to view its message board.</p>


<table id='courseTable'>
	<col width = '150'>
	<col width = '700'>
	<col width = '150'>
	<col width = '150'>
	<% if current_user && current_user.role == 'admin' %>
		<col width = '100'>
		<col width = '100'>
	<% end %>
	<tr class='header'>
		<th>Term</th>
		<th>Course</th>
		<th># of Discussions</th>
		<th># of Tutors</th>
		<% if current_user && current_user.role == 'admin' %>
			<th></th>
			<th></th>
		<% end %>
	</tr>
	<% @courses.order(:term, :name).each do |course| %>
		<tr>
			<td><%= course.term %></td>
			<td><%= link_to(course.name, {:controller => 'messageboard', :action => 'index', :course => course.id}) %></td>
			<td><%= Topic.where(:course_id => course.id).count %></td>
			<% if Tutoring.where(:course_id => course.id).count == 0 %>
				<td>0</td>
			<% else %>
				<td><%= Tutoring.where(:course_id => course.id).count %> (<%= link_to "View Tutors", {:controller => 'tutorings', :action => 'list', :course => course.id} %>)</td>
			<% end %>
			<% if current_user && current_user.role == 'admin' %>
				<td><%= link_to 'Edit', edit_course_path(course) %></td>
				<td><%= link_to 'Delete', course, method: :delete, data: { confirm: 'Are you sure?' } %></td>
			<% end %>
		</tr>
	<% end %>
</table>
<%= render 'event' %>






<head>
  <title>Facebook Auth Example</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div>
<!--
    <%= link_to "Sign in with Facebook", "/auth/facebook", id: "sign_in" %>

-->




</div>
<%= yield %>

</body>
</div>

app/views/courses/new.html.erb
<h1>Add New Course</h1>

<%= render 'form' %>

<p><%= link_to 'Cancel', courses_path %></p>