config/routes.rb
Rails.application.routes.draw do

  resources :events
  post 'reviews/edit', :to => "reviews#edit"
  get 'tutorings/index'
  get 'tutorings/new'
  get 'tutorings/edit'
  get 'tutorings/show'
  get 'tutorings/list'

  post '/rate' => 'rater#create', :as => 'rate'

  get 'fbsessions/create'
  get 'fbsessions/destroy'
  get 'fbsessions/create'
  get 'fbsessions/destroy'
  get 'sessions/create'
  get 'sessions/destroy'

  get 'home/show'

  get "signup", :to => "users#new"
  get "login", :to => "sessions#login"
  get "logout", :to => "sessions#logout"
  get "home", :to => "sessions#home"

  get "setting", :to => "sessions#setting"

  get 'users/list', to: "users#list"
  get 'courses/download', to: "courses#download_request"
  post 'courses/download', to: "courses#download"
  post 'login', :to => "sessions#login_attempt"

  get 'users/new'
  get 'courses/index'
  get 'courses/new'
  get 'posts/index'
  get 'user/profile'
  get 'user/show'
  get 'user/register'
  get 'user/login'
  get 'messageboard/index'
  get 'messageboard/new'
  get 'messageboard/show'

  resources :widgets
  resources :users
  resources :fbsessions
  resources :reviews
  resources :tutorings
  resources :courses do
    member do
      get :subscribe
    end
  end

  resources :messageboard do
    resources :posts
    member do
      get :subscribe
    end
  end
  resources :topic do
    resources :posts
  end
  resources :posts do
    resources :posts
    member do
      put "like", to: "posts#upvote"
      put "dislike", to: "posts#downvote"
    end
  end

  resources :notifications do
    collection do
      post :mark_as_read
    end
  end
  scope '/users' do
    resources :conversations do
      resources :messages
    end
  end

  resources :conversations do
    resources :messages
  end

  get 'auth/:provider/callback', to: 'fbsessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'fbsessions#destroy', as: 'signout'

  resources :fbsessions, only: [:create, :destroy]
  resource :home, only: [:show]

  root to: "courses#index"
  get 'calendars', to: 'calendars#index'

  get '/redirect', to: 'fbsessions#redirect', as: 'redirect'
  get '/callback', to: 'fbsessions#callback', as: 'callback'

end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id            :integer          not null, primary key
#  topic_id      :integer
#  user_id       :integer
#  text          :text
#  rating        :integer
#  anon          :boolean
#  parent        :integer
#  postable_id   :integer
#  postable_type :string
#  deleted       :boolean
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class Post < ActiveRecord::Base
  belongs_to :user
  belongs_to :topic
  belongs_to :postable, polymorphic: true
  has_many :posts, as: :postable
  acts_as_votable

  validates :user_id, :presence =>true
  validates :topic_id, :presence =>true
  validates :anon, :inclusion => {:in => [true, false]}
  validates :deleted, :inclusion => {:in => [true, false]}
  validates :text, presence: true, length: {minimum: 2}

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
before_action :find_postable

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = @postable.posts.new post_params
    @post.user_id = current_user.id
    @post.deleted = false

    if @post.save
      @topic = Topic.find(@post.topic_id)
      @OP = User.find(@topic.user_id)

      ((@topic.users.uniq + [@OP] - [current_user]).uniq).each do |user|
        if user.following?(@topic)
          Notification.create(recipient: user, actor: current_user, action: "New Post in " << @topic.title, notifiable: @topic)
        end
      end

      redirect_to :back, notice: 'Comment posted.'
    else
      redirect_to :back, notice: 'Your comment was not posted.'
    end
  end

  def edit
    @post = Post.find params[:id]
  end

  def update
    @post = Post.find params[:id]
    if @post.update(post_params)
      redirect_to :back, notice: 'Post was successfully updated.'
    else
      redirect_to :back, notice: 'Post was not updated.'
    end
  end

  def destroy
    @post.destroy
    redirect_to :back, notice: 'Post deleted'
  end

  def upvote
    @post = Post.find(params[:id])
    @post.upvote_by current_user
    redirect_to :back
  end

  def downvote
    @post = Post.find(params[:id])
    @post.downvote_by current_user
    redirect_to :back
  end

  private

  def post_params
    params.require(:post).permit(:topic_id, :user_id, :text, :anon, :deleted)
  end

  def find_postable
    @postable = Post.find_by_id(params[:post_id]) if params[:post_id]
    @postable = Topic.find_by_id(params[:topic_id]) if params[:topic_id]
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_post.html.erb
<div class="nested_posts_border">
<div class="nested_posts">

  <div class="post">
    <% if post.deleted == true %>
        <p> [deleted] </p>
    <% else %>   <!-- Start of post -->
        <% if post.anon == true %>
          Anon
        <% else %>
          <a href= <%= user_path('show',id: post.user_id) %>>
            <%= post.user.username unless post.user.blank?%>
          </a>
        <% end %>
      -
      <small>
        <%= time_ago_in_words(post.created_at) %> ago |
        <%= post.cached_votes_score %>
      </small>
      <br/>
      <p>
        <div id="post_body_<%= post.id %>">
         <%= simple_format(post.text) %>
        </div>

        <div id="edit_body_<%= post.id %>" style="display: none;">
          <%= form_for(post) do |f| %>
            <%= f.text_area :text %> <br/>
            <%= f.submit "Save Changes" %>
          <% end %>
        </div>
      </p>

      <p class="post_links">
        <small>
          <a href="#" id="show_comment_box_<%= post.id %>"> Reply </a>
        </small>

        <% if current_user %>
          <small>

            <% if (current_user.id == post.user_id) || (current_user.role == 'admin') %>
              <a href="#" id="edit_toggle_<%= post.id %>"> Edit </a>
            <% end %>

            <% if (current_user.id != post.user_id) %>
              <%= link_to like_post_path(post), method: :put do %>
                  Upvote
              <% end %>

              <%= link_to dislike_post_path(post), method: :put do %>
                Downvote
              <% end %>
            <% end %>

            <% if current_user.role == 'admin' %>
              <%= link_to "Delete",
                  post_path(post, :post => { :deleted => true}),
                  :method => :put,
                  :confirm => "Are you sure?"
              %>
            <% end %>
          </small>
      <% end %>
      </p>

      <div id="hide_comment_box_<%= post.id %>" style="display: none;">
        <% if current_user %>
          <br/>
          <%= form_for [post, Post.new] do |f| %>
            <%= f.text_area :text, placeholder: "Reply to this post" %> <br/>
            <%= f.check_box :anon %>
            <%= f.hidden_field :topic_id, value: t_id %>
            <small> Post anonymously </small> <br/>
            <%= f.submit "Reply"  %>
          <% end %>
          <br />
        <% else %>
          <p> Please log in to reply </p>
        <% end %>
      </div>

    <% end %> <!-- end of post -->

  </div>

  <% if p_order == 'rating' %>
    <%= render(partial: 'posts/post', collection: post.posts.order(cached_votes_score: :desc),
               locals: {t_id: @topic.id, p_order: p_order}) %>
  <% else %>
    <%= render(partial: 'posts/post', collection: post.posts.order(:created_at).reverse_order,
               locals: {t_id: @topic.id, p_order: p_order}) %>
  <% end %>

</div>
</div>


<script>
$(function()
{
  $('a#show_comment_box_<%= post.id %>').click(function(event)
  {
    event.preventDefault();
    $('div#hide_comment_box_<%= post.id %>').toggle();
  });
});

$('#edit_toggle_<%= post.id %>').on('click',function()
{
    if($('#post_body_<%= post.id %>').css('display')!='none')
    {
      $('#edit_body_<%= post.id %>').html($('#edit_body_<%= post.id %>').html()).show().siblings('div').hide();
    }
    else if($('#edit_body_<%= post.id %>').css('display')!='none')
    {
      $('#post_body_<%= post.id %>').show().siblings('div').hide();
    }
});
</script>

app/views/posts/edit.html.erb
<h4> Edit Post </h4>

<%= form_for(@post) do |f| %>
  <%= f.label :text %> <br/>
  <%= f.text_area :text %> <br/>
  <%= f.submit "Edit"  %>
<% end %>

app/views/posts/index.html.erb
<h4> Topic Title </h4>
<p>
<% @posts.each do |post| %>
<%= post.text %>
<% end %>
</p>